name: Deploy Laravel Project on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16.x'

      # - name: Copy .env
      #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # - name: Install Dependencies
        # run: composer update

      # - name: Generate key
      #   run: php artisan key:generate

      # - name: Generate storage link
      #   run: php artisan storage:link

      # - name: Directory Permissions s
      #   run: chmod -R 777 storage bootstrap/cache

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          protocol: ftp
          port: 21
          # timeout: 600000
