name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to vps
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.V_USER }}
        host: ${{ secrets.V_HOST }}
        password: ${{ secrets.V_PASS }}
        script: 'cd /var/www/html/cicd && ./server_deploy.sh'
